### ISSUE TITLE
有vue版本吗

### ISSUE THREAD

**Issue by AmarsDing** [bojue/Web-Editor#38]

**Comment by bojue** [comment]
我只用angular做的，vue我自己还没看过

**Comment by bojue** [comment]
@AmarsDing 我目前只做了angular版本，Vue我自己还没学

**Comment by bojue** [comment]
@AmarsDing 我今天看到一个 [ Vue版本组态 ](https://github.com/phynos/WebTopo/tree/master/src)

**Comment by bojue** [comment]
@AmarsDing 做了一个Vue版本的 [https://github.com/bojue/BaseMap](https://github.com/bojue/BaseMap)
