### ISSUE TITLE
运行项目报错

### ISSUE THREAD

**Issue by ljfass** [bojue/Web-Editor#58]
环境：
@angular/cli: v13.3.0
node: v16.10.0
npm: v67.24.0
os: darwin arm64

重现步骤：
1.npm install
2.npm start

![bug](https://user-images.githubusercontent.com/18080203/164128203-37f9f1d9-f722-4402-8e6f-595d338345c9.png)

**Comment by bojue** [comment]
@ljfass 前两天已经处理了
